### ISSUE TITLE
`ToString` fails for `NULL`?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#111]
```
> toStringNET(NULL)
Error in do.call(".External", c(list("r_call_static_method", typename,  : 
  Type:    System.NullReferenceException
Message: Object reference not set to an instance of an object.
Method:  System.String ToString(System.Object)
Stack trace:
   at ClrFacade.InternalRSharpFacade.ToString(Object obj)
   at ClrFacade.ClrFacade.ToString(Object obj)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
3.
do.call(".External", c(list("r_call_static_method", typename,
methodName), args, PACKAGE = rSharpEnv$nativePkgName)) at utilities-static.R#60
2.
callStatic(rSharpEnv$clrFacadeTypeName, "ToString", x) at utilities.R#34
1.
toStringNET(NULL)

```

`ToString` should catch `NULL` and return `NULL` as string?

**Comment by PavelBal** [comment]
Fixes by https://github.com/Open-Systems-Pharmacology/rSharp/pull/123
